config/routes.rb
Rails.application.routes.draw do

  get '/shop' => 'spree/products#index', as: :products_path
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.add_routes do
    namespace :admin, path: Spree.admin_path do
      resources :reports, only: [:index] do
        collection do
          get :product_summary
          post :product_summary
        end
        collection do
          get :promotion_summary
          post :promotion_summary
        end
      end
    end
  end

end

app/models/product_daily_summary.rb
class ProductDailySummary < ActiveRecord::Base
end

app/models/product_monthly_summary.rb
class ProductMonthlySummary < ActiveRecord::Base
end

app/models/product_yearly_summary.rb
class ProductYearlySummary < ActiveRecord::Base
end

app/models/promotion_daily_summary.rb
class PromotionDailySummary < ActiveRecord::Base
end

app/models/promotion_monthly_summary.rb
class PromotionMonthlySummary < ActiveRecord::Base
end

app/models/promotion_yearly_summary.rb
class PromotionYearlySummary < ActiveRecord::Base
end

app/models/spree/gateway/firstdata_e4.rb
module Spree
   class Gateway::FirstdataE4 < Gateway
     preference :login, :string
     preference :password, :password


     def provider_class
       ActiveMerchant::Billing::FirstdataE4Gateway
     end
   end
end

app/models/spree/gateway/payeezy.rb
# require 'active_merchant'

# module Spree
#    class Gateway::Payeezy < Gateway
#      preference :login, :string
#      preference :password, :password

#      def provider_class
#        ActiveMerchant::Billing::PayeezyGateway
#      end
#    end
# end

app/models/spree/order_decorator.rb
module Spree
	class Order < Spree::Base
	    def empty!
			line_items.destroy_all
			updater.update_item_count
			adjustments.destroy_all
			shipments.destroy_all
			state_changes.destroy_all
			promotions.destroy_all

			update_totals
			persist_totals
	    end
	end
end

app/models/spree/promotion/rules/restrict_free_shipping.rb
module Spree
  class Promotion
    module Rules
      class RestrictFreeShipping < Spree::PromotionRule
   
        def applicable?(promotable)
          promotable.is_a?(Spree::Shipment)
        end

        def eligible?(order, options={})
          e = false
          if order.shipping_method.id == 1
            e = true
          else
            e = false
          end
          return e
        end

      end
    end
  end
end

app/models/spree/promotion_decorator.rb
Spree::Promotion.class_eval do
	def credits_closed
		Spree::Adjustment.eligible.promotion.where(source_id: actions.map(&:id), state: "closed")
	end

	def closed_count
		credits_closed.count
	end
end

app/models/spree/shipment_decorator.rb
Spree::Shipment.class_eval do
  	private
  	def send_shipped_email
	end
end

app/models/spree/shipment_handler_decorator.rb
Spree::ShipmentHandler.class_eval do
  	private
	def send_shipped_email
	end
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do

  before_create :mailchimp_add_to_mailing_list

  def mailchimp_add_to_mailing_list
  	api_key = Rails.application.secrets.MAILCHIMP_API_KEY
    gibbon = Gibbon::Request.new(api_key: api_key)
    list_id = Rails.application.secrets.MAILCHIMP_LIST_ID
    @signupresult = 'success'
    begin
    	gibbon.lists(list_id).members.create(body: {email_address: self.email, status: "subscribed", double_optin: false, send_welcome: false, merge_fields: {FNAME: "", LNAME: ""}})
    rescue Gibbon::MailChimpError => error
      if error.title
        if error.title = "Member Exists"
          @signupresult = "currentmember"
        end
      end
      logger.warn "SpreeMailChimp: Failed to create contact in Mailchimp"
    end

  end
end

app/models/spree/variant_decorator.rb
module Spree
	class Variant < Spree::Base
		def clean_options_text
			values = self.option_values.sort do |a, b|
				a.option_type.position <=> b.option_type.position
			end

		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/admin/reports_controller_decorator.rb
Spree::Admin::ReportsController.class_eval do

	def initialize
		super 
		Spree::Admin::ReportsController.add_available_report!(:sales_total)
		Spree::Admin::ReportsController.add_available_report!(:product_summary)
		Spree::Admin::ReportsController.add_available_report!(:promotion_summary)
	end

	def product_summary
		params[:q] = {} unless params[:q]
		if params[:grouping].blank?
			params[:grouping] = "Daily"
		end

		if params[:q][:completed_at_eq].blank?
			params[:q][:completed_at_eq] = Time.zone.now.beginning_of_day
		else
			params[:q][:completed_at_eq] = Time.zone.parse(params[:q][:completed_at_eq]).beginning_of_day rescue Time.zone.now.beginning_of_day
		end
		if params[:selected_month].blank?
			params[:selected_month] = Time.zone.now.beginning_of_month
		else
			params[:selected_month] = Time.zone.parse(params[:selected_month]).beginning_of_month rescue Time.zone.now.beginning_of_month
		end
		if params[:selected_year].blank?
			params[:selected_year] = Time.zone.now.beginning_of_year
		else
			params[:selected_year] = Time.zone.parse(params[:selected_year]).beginning_of_year rescue Time.zone.now.beginning_of_year
		end

		if params[:grouping] == "Daily"
			@search = ProductDailySummary.ransack(params[:q])
		elsif params[:grouping] == "Monthly"
			params[:q][:completed_at_eq] = params[:selected_month]
			@search = ProductMonthlySummary.ransack(params[:q])
		elsif params[:grouping] == "Yearly"
			params[:q][:completed_at_eq] = params[:selected_year]
			@search = ProductYearlySummary.ransack(params[:q])
		end

		params[:q][:s] ||= "completed_at asc"

		@products = @search.result
    end

	def promotion_summary
		params[:q] = {} unless params[:q]
		if params[:grouping].blank?
			params[:grouping] = "Daily"
		end

		if params[:q][:updated_at_eq].blank?
			params[:q][:updated_at_eq] = Time.zone.now.beginning_of_day
		else
			params[:q][:updated_at_eq] = Time.zone.parse(params[:q][:updated_at_eq]).beginning_of_day rescue Time.zone.now.beginning_of_day
		end
		if params[:selected_month].blank?
			params[:selected_month] = Time.zone.now.beginning_of_month
		else
			params[:selected_month] = Time.zone.parse(params[:selected_month]).beginning_of_month rescue Time.zone.now.beginning_of_month
		end
		if params[:selected_year].blank?
			params[:selected_year] = Time.zone.now.beginning_of_year
		else
			params[:selected_year] = Time.zone.parse(params[:selected_year]).beginning_of_year rescue Time.zone.now.beginning_of_year
		end

		if params[:grouping] == "Daily"
			@search = PromotionDailySummary.ransack(params[:q])
		elsif params[:grouping] == "Monthly"
			params[:q][:updated_at_eq] = params[:selected_month]
			@search = PromotionMonthlySummary.ransack(params[:q])
		elsif params[:grouping] == "Yearly"
			params[:q][:updated_at_eq] = params[:selected_year]
			@search = PromotionYearlySummary.ransack(params[:q])
		end

		params[:q][:s] ||= "completed_at asc"

		@promotions = @search.result
    end
end

app/controllers/spree/home_controller_decorator.rb
Spree::HomeController.class_eval do
	before_filter :home_check
	def home_check
		@home_check = true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spree/frontend_helper_decorator.rb
module Spree
  module FrontendHelper
  	def taxons_tree(root_taxon, current_taxon, max_level = 1)
      return '' if max_level < 1 || root_taxon.leaf?
      content_tag :div, class: 'list-group' do
        taxons = root_taxon.children.map do |taxon|
        	if taxon.products.available.count > 0
				css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'list-group-item active' : 'list-group-item'
				link_to(taxon.name, seo_url(taxon), class: css_class) + taxons_tree(taxon, current_taxon, max_level - 1)
			end
        end
        safe_join(taxons, "\n")
      end
    end
  end
end

app/views/spree/admin/promotions/_form.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @promotion } %>

<div class="row" id="general_fields" >
  <div class="col-md-3">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :code, class: ['form-group'] do %>
      <%= f.label :code %>
      <%= f.text_field :code, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :path, class: ['form-group'] do %>
      <%= f.label :path %>
      <%= f.text_field :path, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :advertise, class: ['checkbox'] do %>
      <%= f.label :advertise do %>
        <%= f.check_box :advertise %>
        <%= Spree.t(:advertise) %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description %>
      <%= f.text_area :description, :rows => 7, :class => 'form-control' %>
    <% end %>

    <%= f.field_container :category, class: ['form-group'] do %>
      <%= f.label :promotion_category %>
      <%= f.collection_select(:promotion_category_id, @promotion_categories, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2' }) %>
    <% end %>
  </div>

  <div id="expiry_fields" class="col-md-3">
    <%= f.field_container :usage_limit do %>
      <%= f.label :usage_limit %>
      <%= f.number_field :usage_limit, :min => 0, :class => 'form-control' %>
      <p class="help-block">
        Usage: <%= @promotion.credits_count %><br/>Submits: <%= @promotion.closed_count %>
      </p>
    <% end %>

    <div id="starts_at_field" class="form-group">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at, :value => datepicker_field_value(@promotion.starts_at), :class => 'datepicker datepicker-from form-control' %>
    </div>

    <div id="expires_at_field" class="form-group">
      <%= f.label :expires_at %>
      <%= f.text_field :expires_at, :value => datepicker_field_value(@promotion.expires_at), :class => 'datepicker datepicker-to form-control' %>
    </div>
  </div>
</div>

app/views/spree/admin/promotions/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Promotion) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_promotion), new_object_url, :class => "btn-success", :icon => 'add' %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_promotions_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>

          <div class="form-group">
            <%= label_tag :q_code_cont, Spree.t(:code) %>
            <%= f.text_field :code_cont, tabindex: 1, class: "form-control" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_path_cont, Spree.t(:path) %>
            <%= f.text_field :path_cont, tabindex: 1, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= label_tag :q_promotion_category_id_eq, Spree.t(:promotion_category) %>
            <%= f.collection_select(:promotion_category_id_eq, @promotion_categories, :id, :name, { :include_blank => Spree.t('match_choices.all') }, { :class => 'select2' }) %>
          </div>
        </div>
      </div>

      <div data-hook="admin_promotions_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @promotions %>

<% if @promotions.any? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:code) %></th>
        <th><%= Spree.t(:description) %></th>
        <th><%= Spree.t(:usage_limit) %></th>
        <th><%= Spree.t(:promotion_uses) %></th>
        <th><%= Spree.t(:expiration) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promotion| %>
        <tr id="<%= spree_dom_id promotion %>">
          <td><%= link_to promotion.name, edit_admin_promotion_path(promotion) %></td>
          <td><%= promotion.code %></td>
          <td><%= promotion.description %></td>
          <td><%= promotion.usage_limit.nil? ? "∞" : promotion.usage_limit  %></td>
          <td>Usage: <%= promotion.credits_count %><br/>Submits: <%=promotion.closed_count %></td>
          <td><%= promotion.expires_at.to_date.to_s(:short_date) if promotion.expires_at %></td>
          <td class="actions actions-2">
            <%= link_to_edit promotion, :no_text => true %>
            <%= link_to_delete promotion, :no_text => true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Promotion)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/reports/product_summary.html.erb
<% content_for :page_title do %>
  Product Summary
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_resource_list, resource: Spree.t(:report)), spree.admin_reports_url, class: 'btn btn-default' %>
<% end %>

<div class="well">
<%= search_form_for @search, :url => spree.product_summary_admin_reports_path  do |s| %>
  <%= render :partial => 'spree/admin/shared/product_summary_criteria', :locals => {:s => s} %>
<% end %>
</div>

<table class="table table-bordered admin-report" data-hook="sales_total">
  <thead>
    <tr>
      <th>Date</th>
      <th>SKU</th>
      <th>Name</th>
      <th>Retail Price</th>
      <th>Items Sold</th>
      <th>Gross Sales</th>
      <th>Discounts</th>
      <th>Net Sales</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <% if params[:grouping] == "Monthly" %>
        <td><%= product.completed_at.year %>-<%= product.completed_at.month %></td>
        <% elsif params[:grouping] == "Yearly" %>
        <td><%= product.completed_at.year %></td>
        <% else %>
        <td><%= product.completed_at %></td>
        <% end %>          
        <td><%= product.sku %></td>
        <td><%= product.name %></td>
        <td><%= product.amount %></td>
        <td><%= product.count %></td>
        <td><%= product.sales %></td>
        <td><%= product.discounts %></td>
        <td><%= product.total_sales %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @products.blank? %>
<div><p>No results for this criteria.</p></div>
<% end %>

app/views/spree/admin/reports/promotion_summary.html.erb
<% content_for :page_title do %>
  Promotion Summary
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_resource_list, resource: Spree.t(:report)), spree.admin_reports_url, class: 'btn btn-default' %>
<% end %>

<div class="well">
<%= search_form_for @search, :url => spree.promotion_summary_admin_reports_path  do |s| %>
  <%= render :partial => 'spree/admin/shared/promotion_summary_criteria', :locals => {:s => s} %>
<% end %>
</div>

<table class="table table-bordered admin-report" data-hook="sales_total">
  <thead>
    <tr>
      <th>Date</th>
      <th>Code</th>
      <th>Name</th>
      <th>Used</th>
      <th>Submitted</th>
    </tr>
  </thead>
  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <% if params[:grouping] == "Monthly" %>
        <td><%= promotion.updated_at.year %>-<%= promotion.updated_at.month %></td>
        <% elsif params[:grouping] == "Yearly" %>
        <td><%= promotion.updated_at.year %></td>
        <% else %>
        <td><%= promotion.updated_at %></td>
        <% end %>          
        <td><%= promotion.code %></td>
        <td><%= promotion.name %></td>
        <td><%= promotion.used %></td>
        <td><%= promotion.submitted %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @promotions.blank? %>
<div><p>No results for this criteria.</p></div>
<% end %>

app/views/spree/admin/shared/_product_summary_criteria.html.erb
<div class="form-group date-range-filter">
  <div class="date-range-filter row">
    <div class="col-md-3">
      <label>Grouping</label>
      <select class="form-control" id="grouping_select">
        <option>Daily</option>
        <option>Monthly</option>
        <option>Yearly</option>
      </select>
      <input type="hidden" id="hidden_grouping" name="grouping" value="Daily">
    </div>
    <div class="col-md-6" id="daily_criteria">
      <label>Date</label>
      <%= s.text_field :completed_at_eq, :class => 'datepicker datepicker-from form-control', :value => datepicker_field_value(params[:q][:completed_at_eq]) %>
    </div>
    <div class="col-md-8" id="monthly_criteria">
      <div class="col-md-3">
        <label>Year</label>
        <select class="form-control year-select">
          <% startyear = 2015 %>
          <% curyear = Time.now.strftime("%Y").to_i %>
          <% until startyear > curyear do %>
            <% if startyear == curyear %>
              <option selected="selected"><%= startyear %></option>
            <% else %>
              <option><%= startyear %></option>
            <% end %>
            <% startyear +=1 %>
          <% end %>
        </select>
      </div>
      <div class="col-md-4">
        <label>Month</label>
        <select class="form-control" id="month-select">
          <% for startmonth in 1..12 %>
            <% if Date::MONTHNAMES[startmonth] == Time.now.strftime("%B") %>
              <option selected="selected" value="<%= startmonth %>"><%= Date::MONTHNAMES[startmonth] %></option>
            <% else %>
              <option value="<%= startmonth %>"><%= Date::MONTHNAMES[startmonth] %></option>
            <% end %>
          <% end %>
        </select>
      </div>
      <input type="hidden" id="selected-month" name="selected_month" value="<%= Time.now.strftime("%m/%Y") %>">
    </div>
    <div class="col-md-3" id="yearly_criteria">
      <label>Year</label>
      <select class="form-control year-select">
        <% startyear = 2015 %>
        <% curyear = Time.now.strftime("%Y").to_i %>
        <% until startyear > curyear do %>
          <% if startyear == curyear %>
            <option selected="selected"><%= startyear %></option>
          <% else %>
            <option><%= startyear %></option>
          <% end %>
          <% startyear +=1 %>
        <% end %>
      </select>
      <input type="hidden" id="selected-year" name="selected_year" value="<%= Time.now.strftime("%Y") %>">
    </div>
  </div>
</div>

<div class="form-actions">
  <%= button Spree.t(:search), 'search' %>
</div>

app/views/spree/admin/shared/_promotion_summary_criteria.html.erb
<div class="form-group date-range-filter">
  <div class="date-range-filter row">
    <div class="col-md-3">
      <label>Grouping</label>
      <select class="form-control" id="grouping_select">
        <option>Daily</option>
        <option>Monthly</option>
        <option>Yearly</option>
      </select>
      <input type="hidden" id="hidden_grouping" name="grouping" value="Daily">
    </div>
    <div class="col-md-6" id="daily_criteria">
      <label>Date</label>
      <%= s.text_field :updated_at_eq, :class => 'datepicker datepicker-from form-control', :value => datepicker_field_value(params[:q][:updated_at_eq]) %>
    </div>
    <div class="col-md-8" id="monthly_criteria">
      <div class="col-md-3">
        <label>Year</label>
        <select class="form-control year-select">
          <% startyear = 2015 %>
          <% curyear = Time.now.strftime("%Y").to_i %>
          <% until startyear > curyear do %>
            <% if startyear == curyear %>
              <option selected="selected"><%= startyear %></option>
            <% else %>
              <option><%= startyear %></option>
            <% end %>
            <% startyear +=1 %>
          <% end %>
        </select>
      </div>
      <div class="col-md-4">
        <label>Month</label>
        <select class="form-control" id="month-select">
          <% for startmonth in 1..12 %>
            <% if Date::MONTHNAMES[startmonth] == Time.now.strftime("%B") %>
              <option selected="selected" value="<%= startmonth %>"><%= Date::MONTHNAMES[startmonth] %></option>
            <% else %>
              <option value="<%= startmonth %>"><%= Date::MONTHNAMES[startmonth] %></option>
            <% end %>
          <% end %>
        </select>
      </div>
      <input type="hidden" id="selected-month" name="selected_month" value="<%= Time.now.strftime("%m/%Y") %>">
    </div>
    <div class="col-md-3" id="yearly_criteria">
      <label>Year</label>
      <select class="form-control year-select">
        <% startyear = 2015 %>
        <% curyear = Time.now.strftime("%Y").to_i %>
        <% until startyear > curyear do %>
          <% if startyear == curyear %>
            <option selected="selected"><%= startyear %></option>
          <% else %>
            <option><%= startyear %></option>
          <% end %>
          <% startyear +=1 %>
        <% end %>
      </select>
      <input type="hidden" id="selected-year" name="selected_year" value="<%= Time.now.strftime("%Y") %>">
    </div>
  </div>
</div>

<div class="form-actions">
  <%= button Spree.t(:search), 'search' %>
</div>

app/views/spree/home/index.html.erb
<div class="hero-image">
	<ul class="slideme">
		<li><%= image_tag "hero_a.jpg" %></li>
		<li><%= image_tag "hero_b.jpg" %></li>
		<li><%= image_tag "hero_c.jpg" %></li>
		<li><%= image_tag "hero_d.jpg" %></li>
		<li><%= image_tag "hero_e.jpg" %></li>
		<li><%= image_tag "hero_f.jpg" %></li>
	</ul>
</div>
<div class="fly-in-steps">
   <div class="fly-in-step step-one"><a href="/shop">APPAREL</a></div>
   <div class="fly-in-step step-two"><a href="/shop">BOX</a></div>
   <div class="fly-in-step step-three"><a href="/shop">VIDEO</a></div>
   <div class="fly-in-step step-four"><a href="/shop">MESSAGE</a></div>
   <div class="fly-in-step step-five"><a href="/shop">SHOP NOW</a></div>
</div>
<div class="arrow"></div>

app/views/spree/layouts/spree_application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
  </head>
  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">
    <%= render partial: 'spree/shared/google_analytics.js' %>
    <%= render partial: 'spree/shared/header' %>
    <%= flash_messages %>
    <% if @home_check %>
    <% else %>
      <div id="main" class="row">
    <% end %>
      <%= yield %>
      <%= yield :templates %>

    <% if @home_check %>
    <% else %>
      </div>
    <% end %>
    <%= render partial: 'spree/shared/footer' %>
    <div class="spinner-wrapper">
      <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>
  </body>
</html>

app/views/spree/layouts/spree_static.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
  </head>
  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">
    <% @static_page = true %>
    <%= render partial: 'spree/shared/google_analytics.js' %>
    <%= render partial: 'spree/shared/header' %>
    <%= flash_messages %>
    <% if @home_check %>
    <% else %>
      <div id="main" class="row">
    <% end %>
      <%= yield %>
      <%= yield :templates %>

    <% if @home_check %>
    <% else %>
      </div>
    <% end %>
    <%= render partial: 'spree/shared/footer' %>
    <div class="spinner-wrapper">
      <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>
  </body>
</html>

app/views/spree/orders/_line_item.html.erb
<% variant = line_item.variant %>

<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <tr class="line-item">
    <td class="cart-item-image" data-hook="cart_item_image">
      <% if variant.images.length == 0 %>
        <%= link_to small_image(variant.product), variant.product %>
      <% else %>
        <%= link_to image_tag(variant.images.first.attachment.url(:small)), variant.product %>
      <% end %>
    </td>
    <td class="cart-item-description" data-hook="cart_item_description">
      <h4><%= link_to line_item.name, product_path(variant.product) %></h4>
      <% variant.clean_options_text.each do |option_text| %>
            <strong><%= option_text.option_type.presentation %></strong>: <%= option_text.presentation %><br/>
          <% end %>
          <% line_item.ad_hoc_option_values.each do |pov| %>
            <strong><%= pov.option_value.option_type.presentation %></strong>: <%= pov.option_value.presentation %><br/>
          <% end %>
          <% line_item.product_customizations.each do |customization| %>
            <strong><%= customization.product_customization_type.presentation %></strong>: <%= customization.customized_product_options[0].value %> %><br/>
          <% end %>
      <% if line_item.insufficient_stock? %>
        <span class="out-of-stock">
          <%= Spree.t(:out_of_stock) %>&nbsp;&nbsp;<br />
        </span>
      <% end %>
      <span class="line-item-description" data-hook="line_item_description">
        <%= line_item_description_text(line_item.description) %>
      </span>
    </td>
    <td class="lead text-primary cart-item-price" data-hook="cart_item_price">
      <%= line_item.single_money.to_html %>
    </td>
    <td class="cart-item-quantity" data-hook="cart_item_quantity" valign="center">
      <%= item_form.number_field :quantity, min: 0, class: "form-control line_item_quantity", size: 5 %>
    </td>
    <td class="lead text-primary cart-item-total" data-hook="cart_item_total">
      <%= line_item.display_amount.to_html unless line_item.quantity.nil? %>
    </td>
    <td class="cart-item-delete" data-hook="cart_item_delete">
      <%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-minus-sign'), '#', class: 'delete', id: "delete_#{dom_id(line_item)}" %>
    </td>
  </tr>
<% end %>